// sample-apps/cometchat-calls-sample-app-svelte/src/App.svelte
<script lang="ts">
  import Router from 'svelte-spa-router';
  import { CometChatCalls } from '@cometchat/calls-sdk-javascript';
  import Login from './pages/login/Login.svelte';
  import JoinSession from './pages/join-session/JoinSession.svelte';
  import Credentials from './pages/credentials/Credentials.svelte';
  import { appStore } from './store/appStore.svelte';

  const routes = {
    '/': Login,
    '/join-session': JoinSession,
    '/credentials': Credentials,
  };

  $effect(() => {
    const { appId, region, authKey } = appStore.credentials;

    if (!appId || !region || !authKey) return;

    const initCometChatCalls = async () => {
      const { error } = await CometChatCalls.init({
        appId,
        region,
        authKey,
      });

      if (error) {
        console.error('CometChatCalls initialization failed:', error);
      } else {
        console.log('CometChatCalls initialized successfully');
      }
    };

    initCometChatCalls();
  });

  $effect(() => {
    const user = CometChatCalls.getLoggedInUser();
    if (user) {
      appStore.setUser(user);
    } else {
      appStore.clearUser();
    }
  });
</script>

<Router {routes} />

// sample-apps/cometchat-calls-sample-app-vue/src/App.vue
<script setup lang="ts">
import { watch, onMounted } from "vue";
import { CometChatCalls } from "@cometchat/calls-sdk-javascript";
import { useAppStore } from "./stores/appStore";
import { useRoute } from "vue-router";

const appStore = useAppStore();
const route = useRoute();

const initCometChatCalls = async () => {
  const { appId, region, authKey } = appStore.credentials;
  if (!appId || !region || !authKey) return;

  const { error } = await CometChatCalls.init({ appId, region, authKey });
  if (error) {
    console.error("CometChatCalls initialization failed:", error);
  } else {
    console.log("CometChatCalls initialized successfully");
  }
};

const checkLoggedInUser = () => {
  const user = CometChatCalls.getLoggedInUser();
  if (user) {
    appStore.setUser(user);
  } else {
    appStore.clearUser();
  }
};

watch(() => appStore.credentials, initCometChatCalls, {
  deep: true,
  immediate: true,
});
watch(() => route.path, checkLoggedInUser);
onMounted(checkLoggedInUser);
</script>

<template>
  <router-view />
</template>
